Fix polling system error introduced by cats-effect update
EpollCat is no longer required (or supported):

java.lang.RuntimeException: Installed PollingSystem does not provide a FileDescriptorPoller
        at java.lang.StackTrace$.currentStackTrace$$anonfun$1(Unknown Source)
        at java.lang.StackTrace$$$Lambda$2.applyVoid(Unknown Source)
        at main @ plutus.Plutus.main(Unknown Source)
        at flatMap @ fs2.io.ioplatform.fileDescriptorPoller(Unknown Source)
        at map @ org.http4s.ember.client.internal.ClientHelpers$.getAddress$$anonfun$2(Unknown Source)
        at flatMap @ org.http4s.ember.client.internal.ClientHelpers$.getAddress(Unknown Source)
        at ref @ fs2.Compiler$Target$ConcurrentTarget.ref(Unknown Source)
[error] java.lang.RuntimeException: Nonzero exit code: 1
[error]         at scala.sys.package$.error(package.scala:30)
[error]         at scala.scalanative.sbtplugin.ScalaNativePluginInternal$.$anonfun$scalaNativeConfigSettings$23(ScalaNativePluginInternal.scala:292)
[error]         at scala.Option.foreach(Option.scala:407)
[error]         at scala.scalanative.sbtplugin.ScalaNativePluginInternal$.$anonfun$scalaNativeConfigSettings$21(ScalaNativePluginInternal.scala:292)
[error]         at scala.scalanative.sbtplugin.ScalaNativePluginInternal$.$anonfun$scalaNativeConfigSettings$21$adapted(ScalaNativePluginInternal.scala:269)
[error]         at scala.Function1.$anonfun$compose$1(Function1.scala:49)
[error] stack trace is suppressed; run last Compile / run for the full output
[error] (Compile / run) Nonzero exit code: 1